<?php

namespace AppBundle\Repository;

/**
 * WarrantyPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarrantyPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
