sylius_resource:
    resources:
        app.warranty_plan:
            classes:
                model: AppBundle\Entity\WarrantyPlan
sylius_customer:
    resources:
        customer:
            classes:
                model: AppBundle\Entity\Customer
