# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_api:
    resource: "@SyliusAdminApiBundle/Resources/config/routing.yml"
    prefix: /api

app_api:
    resource: "routing/api.yml"
    prefix: /api/{version}

app_admin:
    resource: "routing/admin.yml"
    prefix: /admin

app_shop_warranty_plan-index:
    path: /warranty-plans
    defaults:
        _controller: app.controller.warranty_plan:indexAction
        _sylius:
            template: AppBundle::warranty.html.twig

app_shop_warranty_plan.create:
    path: /warranty-plans/create
    defaults:
        _controller: app.controller.warranty_plan:createAction
        _sylius:
            template: AppBundle::warranty_create.html.twig

app_shop_warranty_plan.json:
    path: /plans.json
    defaults:
        _controller: app.controller.warranty_plan:indexAction
        _format: json

sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
