app_admin_warranty_plan:
    resource: |
        alias: app.warranty_plan
        section: admin
        grid: app_admin_warranty_plan
        templates: SyliusAdminBundle:Crud
        redirect: index
    type: sylius.resource
